//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubstringCount.Console.SubstringCountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SubstringCountService.IGetSubstringCountService")]
    public interface IGetSubstringCountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetSubstringCountService/GetSubstringCount", ReplyAction="http://tempuri.org/IGetSubstringCountService/GetSubstringCountResponse")]
        int GetSubstringCount(string message, string substring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetSubstringCountService/GetSubstringCount", ReplyAction="http://tempuri.org/IGetSubstringCountService/GetSubstringCountResponse")]
        System.Threading.Tasks.Task<int> GetSubstringCountAsync(string message, string substring);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetSubstringCountServiceChannel : SubstringCount.Console.SubstringCountService.IGetSubstringCountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSubstringCountServiceClient : System.ServiceModel.ClientBase<SubstringCount.Console.SubstringCountService.IGetSubstringCountService>, SubstringCount.Console.SubstringCountService.IGetSubstringCountService {
        
        public GetSubstringCountServiceClient() {
        }
        
        public GetSubstringCountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetSubstringCountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetSubstringCountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetSubstringCountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetSubstringCount(string message, string substring) {
            return base.Channel.GetSubstringCount(message, substring);
        }
        
        public System.Threading.Tasks.Task<int> GetSubstringCountAsync(string message, string substring) {
            return base.Channel.GetSubstringCountAsync(message, substring);
        }
    }
}
